spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rombokstub
    username: test
    password: test
  flyway:
    validate-migration-naming: true