spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rombokstub
    username: test
    password: test

  graphql:
    graphiql:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
