spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  flyway:
    validate-migration-naming: true
graphql:
  servlet:
    exception-handlers-enabled: true
  graphiql:
    enabled: true
