spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rombokstub
    username: test
    password: test
  jpa:
    show-sql: true

  graphql:
    graphiql:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate:
        type: TRACE
